{
 "title": "Resilience4j",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(resilience4j_circuitbreaker_state, instance)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(resilience4j_circuitbreaker_state, name)"
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": "label_values(resilience4j_retry_calls, name)"
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkead Name",
    "query": "label_values(resilience4j_bulkhead_available_concurrent_calls, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=\"$instance\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "CircuitBreaker, Bulkhead, Retry,  RateLimiter and Timelimiter statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "circuitbreaker_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls{application=\"$application\",name=\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  }
 ]
}