application:
  locale: ru_RU
  empty-item-id: -1

spring:
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    ROOT: debug
    org.springframework.web: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
      enabled: true
      show-components: always
      probes:
        enabled: true
        add-additional-paths: true
      group:
        custom:
          include:
            - diskSpace,ping
    prometheus:
      enabled: true
  health:
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

---
server:
  port: 8090
