INSERT INTO AUTHORS(ID, NAME) VALUES (1, 'Test author 1');
INSERT INTO AUTHORS(ID, NAME) VALUES (2, 'Test author 2');
INSERT INTO AUTHORS(ID, NAME) VALUES (3, 'Test author 3');

INSERT INTO GENRES(ID, NAME) VALUES (1, 'Test genre 1');
INSERT INTO GENRES(ID, NAME) VALUES (2, 'Test genre 2');
INSERT INTO GENRES(ID, NAME) VALUES (3, 'Test genre 3');

INSERT INTO BOOKS(ID, TITLE, ID_AUTHOR, ID_GENRE) VALUES (1, 'Test book 1', 1, 1);
INSERT INTO BOOKS(ID, TITLE, ID_AUTHOR, ID_GENRE) VALUES (2, 'Test book 2', 2, 2);
INSERT INTO BOOKS(ID, TITLE, ID_AUTHOR, ID_GENRE) VALUES (3, 'Test book 3', 3, 3);
