DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS BOOK_COMMENTS;

CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT(100), TITLE VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
CREATE TABLE BOOK_COMMENTS(ID BIGINT PRIMARY KEY AUTO_INCREMENT(100), TEXT VARCHAR(1024), BOOK_ID BIGINT);
