DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT(100), TITLE VARCHAR(255), ID_AUTHOR BIGINT, ID_GENRE BIGINT);
