#server:
#  error:
#    whitelabel:
#      enabled: false
#    include-stacktrace: always
#    include-message: always
#    path: /err
spring:
  mvc:
    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
mongock:
  runner-type: "InitializingBean" # For Spring Shell.
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
logging:
  level:
    ROOT: DEBUG
