application:
  locale: ru_RU
  db-like-template: '%'
spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  shell:
    interactive:
      enabled: true
mongock:
  runner-type: "InitializingBean" # For Spring Shell.
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

---
string-printer:
  columns:
    authors:
      id:
        header: AUTHOR ID
        width: 24
      name:
        header: NAME
        width: 40
    genres:
      id:
        header: GENRE ID
        width: 24
      name:
        header: NAME
        width: 40
    books:
      id:
        header: BOOK ID
        width: 24
      title:
        header: TITLE
        width: 40
      author:
        header: AUTHOR
        width: 30
      genre:
        header: GENRE
        width: 15
    bookComments:
      id:
        header: COMMENT ID
        width: 24
      text:
        header: COMMENT TEXT
        width: 70
