spring:
  profiles:
    active: production
  mvc:
    throw-exception-if-no-handler-found: true
  data:
    mongodb:
      database: librarydb

mongock:
  runner-type: applicationrunner
  migration-scan-package:
    - ru.otus.mongock.changelog
  enabled: true

restservice:
  locale: ru_RU
  mongodb-connection-string: "mongodb://mongodb:27017"
  authors-collection-name: "authors"
  genres-collection-name: "genres"
  books-collection-name: "books"
  comments-collection-name: "book_comments"

server:
  port: 8081

logging:
  level:
    ROOT: WARN
