version: "1.0.0"
services:
  webapp-gateway:
    build: .
    container_name: webapp-gateway
    network_mode: host
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8090" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s
  prometheus:
    image: prom/prometheus:v2.44.0 # has 'wget' utility
    container_name: prometheus-resilience4j
    network_mode: host
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      webapp-gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-O", "index.html", "http://localhost:9090" ]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 60s
  grafana:
    image: grafana/grafana
    container_name: grafana-resilience4j
    env_file:
      - docker/grafana.env
    network_mode: host
