INSERT INTO authors(id, name)
VALUES (1, 'Agatha Christie'),
       (2, 'Alan Bradley'),
       (3, 'Aldous Huxley'),
       (4, 'Alex Michaelides'),
       (5, 'Amal El-Mohtar and Max Gladstone'),
       (6, 'Anaïs Nin'),
       (7, 'Andrzej Sapkowski'),
       (8, 'Anne McCaffrey'),
       (9, 'Anthony Burgess'),
       (10, 'Arthur C. Clarke'),
       (11, 'Attica Locke'),
       (12, 'Audrey Niffenegger'),
       (13, 'Becky Albertalli'),
       (14, 'Becky Chambers'),
       (15, 'Benjamin Alire Sáenz'),
       (16, 'Beverly Jenkins'),
       (17, 'Blanche Wiesen Cook'),
       (18, 'Brandon Sanderson'),
       (19, 'John D. MacDonald'),
       (20, 'C. S. Lewis'),
       (21, 'Caleb Carr'),
       (22, 'Camille Perri'),
       (23, 'Carl Sagan'),
       (24, 'Carlos Ruiz Zafón'),
       (25, 'Casey McQuiston'),
       (26, 'Catherynne M. Valente'),
       (27, 'Charles Yu'),
       (28, 'Charlotte Brontë'),
       (29, 'China Miéville'),
       (30, 'Cixin Liu'),
       (31, 'Clare Lydon'),
       (32, 'Colleen Hoover'),
       (33, 'Colleen McCullough'),
       (34, 'Colson Whitehead'),
       (35, 'Dan Brown'),
       (36, 'Dan Simmons'),
       (37, 'Daniel Jose Older'),
       (38, 'Daphne du Maurier'),
       (39, 'Dashiell Hammett'),
       (40, 'David McCullough'),
       (41, 'Deborah Harkness'),
       (42, 'Dennis Lehane'),
       (43, 'Diana Gabaldon'),
       (44, 'Doris Lessing'),
       (45, 'Douglas Adams'),
       (46, 'E. L. James'),
       (47, 'E.M. Forster'),
       (48, 'Elizabeth Gaskell'),
       (49, 'Emily Brontë'),
       (50, 'Emily Giffin'),
       (51, 'Emily Henry'),
       (52, 'Emily St. John Mandel'),
       (53, 'Frank Herbert'),
       (54, 'Frederick Forsyth'),
       (55, 'Gabriel Garcia Márquez'),
       (56, 'George Orwell'),
       (57, 'George R. R. Martin'),
       (58, 'Georgette Heyer'),
       (59, 'Gillian Flynn'),
       (60, 'Gish Jen'),
       (61, 'H.G. Wells'),
       (62, 'Hafsah Faizal'),
       (63, 'Harlan Coben'),
       (64, 'Haruki Murakami'),
       (65, 'Hayden Herrera'),
       (66, 'Helen Hoang'),
       (67, 'Isaac Asimov'),
       (68, 'Isabel Allende'),
       (69, 'J. R. R. Tolkien'),
       (70, 'Jack Weatherford'),
       (71, 'James M. Cain'),
       (72, 'Jane Austen'),
       (73, 'Jasmine Guillory'),
       (74, 'Jeff VanderMeer'),
       (75, 'Jeffery Deaver'),
       (76, 'Jenny Han'),
       (77, 'Jeong Yu-jeong'),
       (78, 'John Berendt'),
       (79, 'John Green'),
       (80, 'John le Carré'),
       (81, 'Jojo Moyes'),
       (82, 'Jon Krakauer'),
       (83, 'Josephine Tey'),
       (84, 'Judy Blume'),
       (85, 'Kate Atkinson'),
       (86, 'Kazuo Ishiguro'),
       (87, 'Ken Follett'),
       (88, 'Kiera Cass'),
       (89, 'Kim Stanley Robinson'),
       (90, 'Kurt Vonnegut'),
       (91, 'Laura Hillenbrand'),
       (92, 'Laura Kinsale'),
       (93, 'Lee Child'),
       (94, 'Leïla Slimani'),
       (95, 'Leo Tolstoy'),
       (96, 'Liane Moriarty'),
       (97, 'Lincoln Michel'),
       (98, 'Lisa Jewell'),
       (99, 'Lisa Kleypas'),
       (100, 'Loretta Chase'),
       (101, 'Louise Erdich'),
       (102, 'Lucy Foley'),
       (103, 'Madeleine L`Engle'),
       (104, 'Madeline Miller'),
       (105, 'Margaret Atwood'),
       (106, 'Margaret Mitchell'),
       (107, 'Margot Lee Shetterly'),
       (108, 'Mary Shelley'),
       (109, 'Maya Banks'),
       (110, 'N.K. Jemisin'),
       (111, 'Nancy Milford'),
       (112, 'Natsuo Kirino'),
       (113, 'Neal Stephenson'),
       (114, 'Neil Gaiman'),
       (115, 'Nicholas Sparks'),
       (116, 'Nicola Griffith'),
       (117, 'Nnedi Okorafor'),
       (118, 'Nora Roberts'),
       (119, 'Ocean Vuong'),
       (120, 'Octavia Butler'),
       (121, 'Olga Ravn'),
       (122, 'Oyinkan Braithwaite'),
       (123, 'Patricia Briggs'),
       (124, 'Patricia Highsmith'),
       (125, 'Patrick Rothfuss'),
       (126, 'Paula Hawkins'),
       (127, 'PD James'),
       (128, 'Peter Swanson'),
       (129, 'Philip K. Dick'),
       (130, 'Philip Pullman'),
       (131, 'R. F. Kuang'),
       (132, 'Rainbow Rowell'),
       (133, 'Ray Bradbury'),
       (134, 'Raymond Chandler'),
       (135, 'Rebecca Skloot'),
       (136, 'Rick Riordan'),
       (137, 'Riley Sager'),
       (138, 'Rivers Solomon'),
       (139, 'Robert A. Heinlein'),
       (140, 'Robert Coram'),
       (141, 'Robert Jordan and Brandon Sanderson'),
       (142, 'Robert Kanigel'),
       (143, 'Robert Traver'),
       (144, 'Roderick Thorp'),
       (145, 'Roseanne A. Brown'),
       (146, 'Roxane Gay'),
       (147, 'Rüdiger Safranski'),
       (148, 'Ruth Ware'),
       (149, 'S. J. Watson'),
       (150, 'Sabaa Tahir'),
       (151, 'Sally Rooney'),
       (152, 'Sally Thorne'),
       (153, 'Samantha Young'),
       (154, 'Samuel R. Delany'),
       (155, 'Sarah Gailey'),
       (156, 'Sarah Pekkanen'),
       (157, 'Sarah Waters'),
       (158, 'Scott Lynch'),
       (159, 'Sebastian Faulks'),
       (160, 'Silvia Moreno-Garcia'),
       (161, 'Simon Winchester'),
       (162, 'Sir Arthur Conan Doyle'),
       (163, 'Sonia Nazario'),
       (164, 'Stanislaw Lem'),
       (165, 'Stephanie Perkins'),
       (166, 'Stephen Greenblatt'),
       (167, 'Stephen King'),
       (168, 'Stephenie Meyer'),
       (169, 'Stieg Larsson'),
       (170, 'Susan Elizabeth Phillips'),
       (171, 'Susanna Clarke'),
       (172, 'Sylvia Day'),
       (173, 'Sylvia Nasar'),
       (174, 'T. H. White'),
       (175, 'Tade Thompson'),
       (176, 'Tana French'),
       (177, 'Tana French'),
       (178, 'Ted Chiang'),
       (179, 'Terry Goodkind'),
       (180, 'Terry Pratchett'),
       (181, 'Thomas Hardy'),
       (182, 'Thomas Harris'),
       (183, 'Tom Clancy'),
       (184, 'Tomi Adeyemi'),
       (185, 'Toni Cade Bambara'),
       (186, 'Truman Capote'),
       (187, 'Ursula K. Le Guin'),
       (188, 'V. E. Schwab'),
       (189, 'W.E.B. Du Bois'),
       (190, 'Walter Isaacson'),
       (191, 'Walter M. Miller Jr.'),
       (192, 'Wilkie Collins'),
       (193, 'William Gibson'),
       (194, 'William Goldman'),
       (195, 'William Shakespeare'),
       (196, 'Winston Graham'),
       (197, 'André Aciman'),
       (198, 'Zora Neale Hurston'),
       (199, 'Zoraida Córdova'),
       (200, 'Adam Silvera');
